### ISSUE TITLE
论文链接

### ISSUE THREAD

**Issue by shenbuguanni** [wangtianrui/APC-SNR#2]
你好，这篇论文在网上已经找不到pdf文件，可以分享一下吗？谢谢！

**Comment by wangtianrui** [comment]
由于工作量有限，该损失函数被并入我的一篇期刊论文了，所以把之前单独的介绍paper撤掉了，以下是期刊论文链接：
https://ieeexplore.ieee.org/abstract/document/10147245

**Comment by shenbuguanni** [comment]
> 由于工作量有限，该损失函数被并入我的一篇期刊论文了，所以把之前单独的介绍paper撤掉了，以下是期刊论文链接： https://ieeexplore.ieee.org/abstract/document/10147245

非常感谢，我已经下载进行研读了，这里有个疑问请教一下：
1. ((clean_power + self.eps) ** ((self.zwicker_power - 1) * 0.5)) 代码和论文在这个地方有点不一样，代码多了个0.5,论文没有乘；
2. 另外，经过debug发现这个响度功率压缩让clean信号的TF-能量变小后去计算TF-SNR,这和常规的幂律压缩刚好相反，请问让有信号的时频点能量变小的实际意义是什么呢？
3. 另外，对target和网络输出信号都做LC压缩，只是作用于求loss，并不直接改变网络的输出风格，所以这样求loss怎么让模型输出音频的听觉感知更佳的？
