### ISSUE TITLE
bark_matrix_16k.mat

### ISSUE THREAD

**Issue by smylab** [wangtianrui/APC-SNR#3]
Dear author,

Hello, and thank you for generously sharing this code. I have a question that I would like to seek your advice on. Regarding the calculation of PMSQE, the code includes a file named "bark_matrix_16k.mat" based on a window length of 512 at a 16K sampling rate. I am interested in obtaining a "bark_matrix" for a frame length of 256. Upon careful examination of the code, it seems there is no specific section addressing the retrieval or generation of the "bark_matrix."

Therefore, I am reaching out to you for guidance on how to obtain the "bark_matrix" for a frame length of 256. I appreciate your assistance and look forward to your response.

Best regards,

Mingyue

**Comment by wangtianrui** [comment]
Bark_matrix is the conversion kernel for fbank feature, maybe you can calculate it by librosa with 256 window length like:  lib.filters.mel(sr=16000, n_fft=256, n_mels=80)
